baseURL: http://reidmitchell.net/

languageCode: en-us
title: Reid Mitchell
disqusShortname: reidmitchell
theme: rm
publishDir: docs
pygmentsCodeFences: true

params:
  displayTitle: reid mitchell
  description: Writings and projects from Reid Mitchell, software engineer and filmmaker.

menu:
  main:
    - Name: 'writing'
      Identifier: 'posts'
      URL: '/posts'
      Weight: 1
    - Name: 'code projects'
      Identifier: 'code'
      URL: '/code'
      Weight: 2
    - Name: 'films'
      Identifier: 'films'
      URL: '/films'
      Weight: 3
    - Name: 'about'
      Identifier: 'about'
      URL: '/pages/about'
      Weight: 1000

